config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show]

  resources :spots

  root 'spots#index'

  get  '/users' => redirect('/')

  resources :spots do
    resource :likes, only: [:create, :destroy]
  end

  resources :spots do
    resource :comments, only: [:create]
  end

  resources :comments, only: [:destroy]
end

app/models/spot.rb
class Spot < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  belongs_to :region
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :name, presence: true
  validates :content, presence: true
  validates :region_id, presence: true, numericality: {greater_than: 0}

  mount_uploader :image, ImageUploader
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :search

  def search
    @q = Spot.ransack(params[:q])
    @q.combinator = 'or'
  end

  def index
    @spots = @q.result(distinct: true)
  end
  
  def new
    @spot = Spot.new
  end
    
  def create
    @spot = Spot.new(spots_params)
    if @spot.save
        flash[:notice] = 'スポット登録が完了しました。'
        redirect_to "/spots/#{@spot.id}"
    else
        render('spots/new')
    end
  end

  def destroy
    @spot = current_user.spots.find_by(id: params[:id])
    @spot.destroy
    redirect_to "/"
  end

  def show
    @spot = Spot.find_by(id: params[:id])
    @comments = @spot.comments
    if user_signed_in?
      @comment = current_user.comments.new
    end
  end

  def edit
    @spot = Spot.find_by(id: params[:id])
  end

  def update
    @spot = Spot.find_by(id: params[:id])
    if @spot.update(spots_params)
      flash[:notice] = 'スポット編集が完了しました。'
      redirect_to "/spots/#{@spot.id}"
    else
      render('spots/edit')
    end
  end

  private
  def spots_params
    params.require(:spot).permit(:name, :content, :region_id, :image).merge(user_id: current_user.id)
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/edit.html.erb
<% if @spot.user_id == current_user.id %>
  <h1 class='mb-4'>編集する</h1>
    <div class='form'>
      <%= form_with model: @spot, local: true do |f| %>
      <div class='row gx-2 mb-4'>
        <label class='col-md-1 col-form-label text-md-end'><%= f.label :'スポット名' %></label>
        <div class='col-md-7'>
          <input type='text' class='form-control shadow' name='spot[name]' id='spot_name' value='<%= @spot.name %>'>
        </div>
      </div>

      <div class='row gx-2 mb-4'>
        <label class='col-md-1 col-form-label text-md-end'><%= f.label :'スポット詳細' %></label>
        <div class='col-md-7'>
          <textarea rows='10' class='form-control shadow' name='spot[content]' id='spot_content'><%= @spot.content %></textarea>
        </div>
      </div>

      <div class='row gx-2 mb-4'>
        <label class='col-md-1 col-form-label text-md-end'><%= f.label :region_id, '都道府県' %></label>
        <%= f.collection_select :region_id, Region.all, :id, :name, { prompt: '選択してください' }, autocomplete: 'region_id', class:'form-select- col-md-3 btn btn-secondary shadow' %>
      </div>

      <div class='row gx-2 mb-4'>
        <label class='col-md-1 col-form-label text-md-end'><%= f.label :'写真' %></label>
        <%= f.label :image, 'ファイルを選択してください', class:'form-select- col-md-3 btn btn-secondary shadow' %>
        <%= f.file_field :image, style: 'display: none;' %>
        <%= f.hidden_field :image_cache %><br>
      </div>

      <div class='row gx-2 mb-5'>
        <div class='col-8 text-end'>
          <%= f.submit '編集', class: 'btn btn-primary px-3 shadow' %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h4>投稿したユーザーのみが編集できます。</h4>
<% end %>

app/views/spots/index.html.erb
<h1 class='mb-4'>検索する</h1>
<div class='form'>
  <%= search_form_for @q do |f| %>
    <div class='row gx-2 mb-4'>
      <label class='col-md-1 col-form-label text-md-end'><%= f.label :'スポット名' %></label>
      <%= f.search_field :name_cont, placeholder: 'スポット名を入力してください', class:'form-control- col-md-6 shadow' %>
      <button type="submit" class="fa form-control- col-md-1 btn btn-primary shadow">
        <i class="fa fa-search"></i>&nbsp;検索
      </button>
    </div>

    <div class='row gx-2 mb-4'>
      <label class='col-md-1 col-form-label text-md-end'><%= f.label :'スポット詳細' %></label>
      <%= f.search_field :content_cont, placeholder: 'キーワードを入力してください（安い、広い、貸切など）', class:'form-control- col-md-6 shadow' %>
      <button type="submit" class="fa form-control- col-md-1 btn btn-primary shadow">
        <i class="fa fa-search"></i>&nbsp;検索
      </button>
    </div>

    <div class='row gx-2 mb-4'>
      <label class='col-md-1 col-form-label text-md-end'><%= f.label :region_id, '都道府県' %></label>
      <%= f.collection_select :region_id_eq, Region.all, :id, :name, { prompt: '選択してください' }, 
      autocomplete: 'region_id', class:'form-select- col-md-3 btn btn-secondary shadow' %>
      <button type="submit" class="fa form-control- col-md-1 btn btn-primary shadow">
        <i class="fa fa-search"></i>&nbsp;検索
      </button>
    </div>
  <% end %>
</div>
<div class='row mt-5 mb-4'>
  <% if @q.conditions.present? && @spots.present? %>
    <% @spots.each do |spot| %>
      <div class='col-md-8 bg-light border rounded shadow row mb-4 ms-1 py-2'>
        <div class='col-md-10'>
          <% if user_signed_in? %>
            <% if current_user.liked?(spot) %>
              <%= button_to spot_likes_path(spot), class:'like-btn bg-light border-0', method: :delete do %>
                <%= link_to spot.name + '（' + spot.region.name + '）', "/spots/#{spot.id}", class: 'btn btn-secondary shadow ps-3' %>
                <div class='btn btn-light btn-lg text-danger ms-2'>
                  <span class='fa fa-heart'></span>
                  <span class='like__count'><%= spot.likes.count %></span>
                </div>
              <% end %>
            <% else %>
              <%= button_to spot_likes_path(spot), class:'like-btn bg-light border-0', method: :post do %>
                <%= link_to spot.name + '（' + spot.region.name + '）', "/spots/#{spot.id}", class: 'btn btn-secondary shadow ps-3' %>
                <div class='btn btn-light btn-lg text-danger ms-2'>
                  <span class='fa fa-heart-o'></span>
                  <span class='like__count'><%= spot.likes.count %></span>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to spot.name + '（' + spot.region.name + '）', "/spots/#{spot.id}", class: 'btn btn-secondary shadow ps-3' %>
            <div class='btn btn-light btn-lg text-danger ms-2'>
              <span class='fa fa-heart-o'></span>
              <span class='like__count'><%= spot.likes.count %></span>
            </div>
          <% end %>
          <div class='mt-2 mx-2 mb-1'>
            <%= safe_join(spot.content.split("\n"),tag(:br)) %>
          </div>
        </div>
        <div class='col-md-2 d-flex align-items-center'>
          <% if spot.image.url %>
            <%= image_tag spot.image.thumb50.url %>
          <% end %>
        </div>
      </div>
    <% end %>
  <%else %>
    <h4>検索結果はありません。</h4>
  <% end %>
</div>

app/views/spots/new.html.erb
<h1 class='mb-4'>登録する</h1>
<div class='form'>
  <%= form_with model: @spot, local: true do |f| %>
    <div class='row gx-2 mb-4'>
      <label class='col-md-1 col-form-label text-md-end'><%= f.label :'スポット名' %></label>
      <div class='col-md-7'>
        <input type='text' class='form-control shadow' name='spot[name]' id='spot_name'>
      </div>
    </div>

    <div class='row gx-2 mb-4'>
      <label class='col-md-1 col-form-label text-md-end'><%= f.label :'スポット詳細' %></label>
      <div class='col-md-7'>
        <textarea rows='10' class='form-control shadow' name='spot[content]' id='spot_content'></textarea>
      </div>
    </div>

    <div class='row gx-2 mb-4'>
      <label class='col-md-1 col-form-label text-md-end'><%= f.label :region_id, '都道府県' %></label>
      <%= f.collection_select :region_id, Region.all, :id, :name, { prompt: '選択してください' }, autocomplete: 'region_id', class:'form-select- col-md-3 btn btn-secondary shadow' %>
    </div>

    <div class='row gx-2 mb-4'>
      <label class='col-md-1 col-form-label text-md-end'><%= f.label :'写真' %></label>
      <%= f.label :image, 'ファイルを選択してください', class:'form-select- col-md-3 btn btn-secondary shadow' %>
      <%= f.file_field :image, style: 'display: none;' %>
      <%= f.hidden_field :image_cache %><br>
    </div>

    <div class='row gx-2 mb-5'>
      <div class='col-8 text-end'>
        <%= f.submit '登録', class: 'btn btn-primary px-3 shadow' %>
      </div>
    </div>
  <% end %>
</div>

app/views/spots/show.html.erb
<div class='row mb-5'>
  <div class='bg-light border rounded shadow p-4 col-md-8'>
    <div class='mt-2 mb-4'>
      <h1><%= @spot.name %>（<%= @spot.region.name %>）</h1>
    </div>

    <div class='image'>
      <% if @spot.image.url %>
        <%= image_tag @spot.image.thumb.url, class:'mt-2 mb-4' %>
      <% end %>
    </div>

    <div class='like-btn'>
      <% if user_signed_in? %>
        <% if current_user.liked?(@spot) %>
          <%= button_to spot_likes_path(@spot), class:'like-btn bg-light border-0', method: :delete do %>
            <div class='btn btn-light btn-lg text-danger mb-4'>
              <span class='fa fa-heart'></span>
              <span class='like__count'><%= @spot.likes.count %></span>
            </div>
          <% end %>
        <% else %>
          <%= button_to spot_likes_path(@spot), class:'like-btn bg-light border-0', method: :post do %>
            <div class='btn btn-light btn-lg text-danger mb-4'>
              <span class='fa fa-heart-o'></span>
              <span class='like__count'><%= @spot.likes.count %></span>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class='btn btn-light btn-lg text-danger mb-4'>
          <span class='fa fa-heart-o'></span>
          <span class='like__count'><%= @spot.likes.count %></span>
        </div>
      <% end %>
    </div>

    <div class='mb-5'>
      <p><%= safe_join(@spot.content.split("\n"),tag(:br)) %></p>
    </div>

    <div class='mb-5'>
      <% if user_signed_in? && @spot.user_id == current_user.id %>
        <%= link_to 'スポット編集', "/spots/#{@spot.id}/edit", class: 'btn btn-secondary px-3 mb-2 shadow' %><br>
        <%= button_to 'スポット削除', "/spots/#{@spot.id}", method: :delete, data: {confirm: "スポットを削除してもよろしいですか？"}, class: 'btn btn-danger px-3 shadow' %>
      <% end %>
    </div>

    <div class='comments'>
      <h4>コメント</h4>
      <div class='my-3'>
        <% if @comments.empty? %>
          <h6 class='my-5'>コメントはありません。</h6>
        <% else %>
          <% @comments.each do |comment| %>
            <div class='my-2'>
            ・<%= comment.content %>
              (<%= comment.user.name %>さん)
              <% if user_signed_in? && comment.user_id == current_user.id %>
                <%= button_to '削除', comment_path(comment.id), method: :delete, class: 'btn btn-danger btn-sm px-3 mt-1 mb-2 ms-2 shadow' %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class='row gx-2'>
        <% if user_signed_in? %>
          <%= form_with model: [@spot, @comment], local: true do |f| %>
            <div class='comments-new'>
              <textarea rows='10' class='form-control mb-3 shadow' name='comment[content]' id='comment_content'></textarea>
            </div>
            <%= f.hidden_field :post_id, value: @spot.id %>
            <div class='row gx-2'>
              <div class='col-12 text-end'>
                <%= f.submit 'コメントする', class: 'btn btn-primary px-3 shadow' %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>