config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show]

  resources :spots

  root 'spots#index'

  get  '/users' => redirect('/')

  resources :spots do
    resource :likes, only: [:create, :destroy]
  end

  resources :spots do
    resource :comments, only: [:create]
  end

  resources :comments, only: [:destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='is-slide bg' id='page-animate'>
    <div class='fullheight pb-5'>
      <header class='sticky-top'>
        <div class='header-inner border rounded shadow row d-flex align-items-center'>
          <div class='ms-5 col-md-3'>
            <%= link_to 'ダンス大好き！', '/', class: 'title', data: {"turbolinks" => false} %>
          </div>

          <div class='d-flex justify-content-end col-md-8'>
            <%- if user_signed_in? %>
              <div class='mt-2 me-2 pt-3'>
                <%= link_to 'スポット登録', '/spots/new', class: 'btn btn-secondary px-3 shadow' %><br />
              </div>

              <div class='mt-2 mx-2 pt-3'>
                <%= link_to 'マイページ', "/users/#{current_user.id}", class: 'btn btn-secondary px-3 shadow' %><br />
              </div>

              <div class='mt-2 ms-2 pt-3'>
                <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-secondary px-3 shadow' %><br />
              </div>

            <%- else %>
              <div class='py-3'>
                <%= link_to 'ログイン', new_session_path(resource_name), class: 'btn btn-secondary m-2 px-3 shadow' %><br />
              </div>

              <div class='my-2 ms-2 py-3'>
                <%= link_to 'アカウント登録', new_registration_path(resource_name), class: 'btn btn-secondary px-3 shadow' %><br />
              </div>
            <%- end %>
          </div>
        </div>
      </header>
      <main class='mx-5'>
        <div class='greeting'>
          <% if current_user.present? %>
            <h4 class='mt-5 pt-3'>こんにちは、<%= current_user.name %>さん！<br>踊れるスポットを検索できるアプリです！</h4>
          <% else %>
            <h4 class='mt-5 pt-3'>こんにちは、ゲストさん！<br>踊れるスポットを検索できるアプリです！</h4>
          <% end %>
        </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <script src="js/bootstrap.bundle.min.js"></script>
      <%= yield %>
      </main>
    </div>
  </body>
</html>